/*
  Один шейдер на всё: осколки вазы, постамент и «призраки» осколков.
  uMode  0 — ваза (текстура снаружи, тёмная глина внутри), 1 — однотонный материал (постамент)
  uGhost > 0 — рисуем полупрозрачный золотистый контур места осколка
  uGold  0..1 — трещины превращаются в золото (кинцуги) после сборки
*/
window.Shaders = {
  vertex: [
    'attribute vec3 aPos;',
    'attribute vec3 aNor;',
    'attribute vec2 aUV;',
    'attribute float aCrack;',
    'uniform mat4 uModel;',
    'uniform mat3 uRot;',
    'uniform mat4 uViewProj;',
    'varying vec3 vN;',
    'varying vec3 vW;',
    'varying vec2 vUV;',
    'varying float vCrack;',
    'void main() {',
    '  vec4 w = uModel * vec4(aPos, 1.0);',
    '  vW = w.xyz;',
    '  vN = uRot * aNor;',
    '  vUV = aUV;',
    '  vCrack = aCrack;',
    '  gl_Position = uViewProj * w;',
    '}'
  ].join('\n'),

  fragment: [
    '#ifdef GL_FRAGMENT_PRECISION_HIGH',
    'precision highp float;',
    '#else',
    'precision mediump float;',
    '#endif',
    'varying vec3 vN;',
    'varying vec3 vW;',
    'varying vec2 vUV;',
    'varying float vCrack;',
    'uniform sampler2D uTex;',
    'uniform vec3 uEye;',
    'uniform vec3 uLight;',
    'uniform vec3 uColor;',
    'uniform float uMode;',
    'uniform float uGhost;',
    'uniform float uFlash;',
    'uniform float uGold;',
    'uniform float uTime;',
    'void main() {',
    '  vec3 n = normalize(vN);',
    '  vec3 V = normalize(uEye - vW);',
    '  float inside = 0.0;',
    '  if (dot(n, V) < 0.0) { n = -n; inside = 1.0; }',
    '  vec3 L = normalize(uLight);',
    '',
    '  if (uGhost > 0.0) {',
    '    float d = max(dot(n, L), 0.0);',
    '    gl_FragColor = vec4(vec3(1.0, 0.82, 0.42) * (0.55 + 0.45 * d), uGhost);',
    '    return;',
    '  }',
    '',
    '  vec3 base;',
    '  if (uMode > 0.5) base = uColor;',
    '  else if (inside > 0.5) base = vec3(0.34, 0.16, 0.08);',
    '  else base = texture2D(uTex, vUV).rgb;',
    '',
    '  float crack = (uMode > 0.5) ? 0.0 : vCrack;',
    '  vec3 crackCol = mix(vec3(0.07, 0.04, 0.03), vec3(1.0, 0.78, 0.28), uGold);',
    '  base = mix(base, crackCol, crack * 0.9);',
    '',
    '  float diff = max(dot(n, L), 0.0);',
    '  float hemi = 0.5 + 0.5 * n.y;',
    '  vec3 amb = mix(vec3(0.22, 0.18, 0.20), vec3(0.42, 0.38, 0.36), hemi);',
    '  vec3 H = normalize(L + V);',
    '  float sp = pow(max(dot(n, H), 0.0), (uMode > 0.5) ? 16.0 : 48.0);',
    '  float specK = ((uMode > 0.5) ? 0.12 : 0.28) + crack * uGold * 1.4;',
    '  float fres = pow(1.0 - max(dot(n, V), 0.0), 3.0);',
    '',
    '  vec3 col = base * (amb + vec3(1.0, 0.93, 0.82) * diff * 0.85);',
    '  col += vec3(1.0, 0.93, 0.8) * sp * specK;',
    '  col += vec3(0.9, 0.6, 0.35) * fres * 0.18;',
    '  col += uFlash * vec3(1.0, 0.82, 0.35) * 0.55;',
    '  col += crack * uGold * vec3(0.5, 0.35, 0.1) * (0.5 + 0.5 * sin(uTime * 2.0 + vW.y * 4.0)) * 0.35;',
    '  gl_FragColor = vec4(col, 1.0);',
    '}'
  ].join('\n')
};
